import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib"
import type { ParsedFinancialReport } from "@/lib/qbo-financials"

type PdfMetric = {
  label: string
  value: number | null
}

export async function buildFinancialReportPdf(params: {
  companyName?: string | null
  title: string
  rangeLabel: string
  report: ParsedFinancialReport
  metrics: PdfMetric[]
}) {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([792, 612])
  const { width, height } = page.getSize()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold)

  page.drawRectangle({
    x: 0,
    y: height - 88,
    width,
    height: 88,
    color: rgb(0.05, 0.1, 0.16),
  })

  page.drawText(params.title, {
    x: 36,
    y: height - 42,
    size: 24,
    font: fontBold,
    color: rgb(1, 1, 1),
  })

  page.drawText(params.companyName || "BookKeeping.business", {
    x: 36,
    y: height - 62,
    size: 11,
    font,
    color: rgb(0.83, 0.88, 0.94),
  })

  page.drawText(params.rangeLabel, {
    x: width - 200,
    y: height - 60,
    size: 11,
    font,
    color: rgb(0.83, 0.88, 0.94),
  })

  let cursorY = height - 118

  for (const metric of params.metrics.slice(0, 4)) {
    page.drawRectangle({
      x: 36,
      y: cursorY - 34,
      width: 170,
      height: 30,
      color: rgb(0.95, 0.97, 0.99),
      borderColor: rgb(0.88, 0.91, 0.95),
      borderWidth: 1,
    })
    page.drawText(metric.label, {
      x: 44,
      y: cursorY - 18,
      size: 9,
      font,
      color: rgb(0.34, 0.4, 0.46),
    })
    page.drawText(formatCurrency(metric.value), {
      x: 44,
      y: cursorY - 30,
      size: 12,
      font: fontBold,
      color: rgb(0.07, 0.11, 0.16),
    })
    cursorY -= 38
  }

  let tableY = height - 122
  const startX = 240
  const labelWidth = 290
  const valueWidth = 190

  drawTableHeader(page, fontBold, startX, tableY, labelWidth, valueWidth, params.report.columns)
  tableY -= 22

  for (const row of params.report.rows.slice(0, 26)) {
    if (tableY < 36) break
    const fillColor =
      row.rowType === "section" ? rgb(0.96, 0.97, 0.99) :
      row.rowType === "summary" ? rgb(0.94, 0.97, 0.95) :
      undefined

    if (fillColor) {
      page.drawRectangle({
        x: startX,
        y: tableY - 4,
        width: labelWidth + valueWidth,
        height: 18,
        color: fillColor,
      })
    }

    const label = `${"  ".repeat(row.depth)}${row.label}`.slice(0, 56)
    const value = (row.values.at(-1) ?? row.values[0] ?? "—").slice(0, 20)

    page.drawText(label, {
      x: startX + 6,
      y: tableY,
      size: 9,
      font: row.rowType === "summary" || row.rowType === "section" ? fontBold : font,
      color: rgb(0.07, 0.11, 0.16),
    })

    page.drawText(value || "—", {
      x: startX + labelWidth + 6,
      y: tableY,
      size: 9,
      font: row.rowType === "summary" ? fontBold : font,
      color: rgb(0.07, 0.11, 0.16),
    })

    tableY -= 18
  }

  page.drawText("Generated by BookKeeping.business Financials", {
    x: 36,
    y: 18,
    size: 9,
    font,
    color: rgb(0.48, 0.55, 0.61),
  })

  return pdf.save()
}

function drawTableHeader(
  page: PDFPage,
  fontBold: PDFFont,
  x: number,
  y: number,
  labelWidth: number,
  valueWidth: number,
  columns: string[]
) {
  page.drawRectangle({
    x,
    y: y - 4,
    width: labelWidth + valueWidth,
    height: 18,
    color: rgb(0.05, 0.1, 0.16),
  })
  page.drawText(columns[0] ?? "Category", {
    x: x + 6,
    y,
    size: 9,
    font: fontBold,
    color: rgb(1, 1, 1),
  })
  page.drawText(columns.at(-1) ?? "Amount", {
    x: x + labelWidth + 6,
    y,
    size: 9,
    font: fontBold,
    color: rgb(1, 1, 1),
  })
}

function formatCurrency(value: number | null) {
  if (value === null || Number.isNaN(value)) return "—"
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value)
}
